concurrency:
  cancel-in-progress: true
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
jobs:
  test-coverage:
    if: github.repository == 'opengoofy/hippo4j'
    name: Test coverage report
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Cache Maven Repos
      uses: actions/cache@v3
      with:
        key: hippo4j-maven-third-party-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'hippo4j-maven-third-party-

          '
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Test with Maven
      run: echo y | mvn -T1C clean install -Dskip.gpg=true -Dspotless.apply.skip=true
        -Dskip.jacoco.plugin=false
    - continue-on-error: true
      name: Upload to Codecov
      run: bash <(curl -s https://codecov.io/bash)
  unix:
    name: JDK ${{ matrix.java.version }} - on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Build with Maven
      run: echo y | mvn clean install -Dskip.gpg=true -Dspotless.apply.skip=true -Dmaven.javadoc.skip=true
    strategy:
      matrix:
        java:
        - version: 11
        - version: 17
        os:
        - macos-latest
    timeout-minutes: 60
name: build
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
