jobs:
  contrib-readme-job:
    name: A job to automate contrib in readme
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      name: Contribute List
      uses: akhilmhdh/contributors-readme-action@v2.3.6
      with:
        columns_per_row: 9
        commit_message: Update the list of contributors
        committer_email: wechat202110@163.com
        committer_username: hippo4jbot[bot]
        image_size: 50
on:
  repository_dispatch:
    types: trigger-ga___reademe-contributors.yml
